// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwxZqJRNtzvZP5AcAuMRtsJvuBlsQuo3E',
    appId: '1:336831605891:web:ca1a1e6bbdd4da66aa3fb6',
    messagingSenderId: '336831605891',
    projectId: 'movietv-a324c',
    authDomain: 'movietv-a324c.firebaseapp.com',
    storageBucket: 'movietv-a324c.appspot.com',
    measurementId: 'G-YC1QX4CSGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr7km1jgc2yY1uhdUyz3jood4V8wLR09A',
    appId: '1:336831605891:android:f1b4ced3e0d55cf6aa3fb6',
    messagingSenderId: '336831605891',
    projectId: 'movietv-a324c',
    storageBucket: 'movietv-a324c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5JWA_FZn1xc4FrSv3Cw8cGULdZFfD3g',
    appId: '1:336831605891:ios:65a404704d41f55daa3fb6',
    messagingSenderId: '336831605891',
    projectId: 'movietv-a324c',
    storageBucket: 'movietv-a324c.appspot.com',
    iosClientId: '336831605891-pu1jbp2onr1gr68mcj8tjeedcg94bavp.apps.googleusercontent.com',
    iosBundleId: 'com.example.movietv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5JWA_FZn1xc4FrSv3Cw8cGULdZFfD3g',
    appId: '1:336831605891:ios:65a404704d41f55daa3fb6',
    messagingSenderId: '336831605891',
    projectId: 'movietv-a324c',
    storageBucket: 'movietv-a324c.appspot.com',
    iosClientId: '336831605891-pu1jbp2onr1gr68mcj8tjeedcg94bavp.apps.googleusercontent.com',
    iosBundleId: 'com.example.movietv',
  );
}
